# Generated by Django 2.2 on 2019-05-24 07:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('py', 'Python'), ('dj', 'Django'), ('ui', 'UI'), ('rest', 'Rest API')], max_length=200)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('mrg', 'Morning'), ('aftn', 'AfterNoon'), ('evng', 'Evening'), ('night', 'Night')], max_length=200)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'Hyderabad'), ('bang', 'Banglore'), ('che', 'Chennai'), ('pune', 'Pune')], max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('start_date', models.DateField(max_length=50)),
            ],
        ),
    ]
