# Generated by Django 2.2 on 2019-05-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_contactdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
