# Generated by Django 2.2 on 2019-05-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_coursesdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesdata',
            name='start_time',
            field=models.TimeField(max_length=100),
        ),
    ]
